apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: concourse-ci-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: concourse-ci-cleanup
subjects:
- kind: ServiceAccount
  name: concourse-ci-cleanup
  namespace: concourse
